name: ra_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py38h06a4308_0
  - python=3.8.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - colorama==0.4.6
    - cycler==0.11.0
    - deprecated==1.2.14
    - docker-pycreds==0.4.0
    - fonttools==4.42.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.57.0
    - h5py==3.9.0
    - humanize==4.8.0
    - idna==3.4
    - imageio==2.31.2
    - importlib-metadata==6.8.0
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lightning-utilities==0.9.0
    - llvmlite==0.40.1
    - lpips==0.1.4
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.5.1
    - mdurl==0.1.2
    - monai==0.8.1
    - multidict==6.0.4
    - networkx==3.1
    - nibabel==3.2.2
    - numba==0.57.1
    - numpy==1.21.5
    - oauthlib==3.2.2
    - opencv-python==4.8.0.76
    - packaging==23.1
    - pandas==2.0.3
    - pathtools==0.1.2
    - pillow==10.0.0
    - plotly==5.16.1
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.5
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydeprecate==0.3.1
    - pydicom==2.4.3
    - pygments==2.16.1
    - pynndescent==0.5.10
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.10
    - pytorch-msssim==1.0.0
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.5.2
    - rsa==4.9
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - sentry-sdk==1.30.0
    - setproctitle==1.3.2
    - setuptools==59.5.0
    - shellingham==1.5.3
    - shortuuid==1.0.11
    - simpleitk==2.2.1
    - six==1.16.0
    - smmap==5.0.0
    - tenacity==8.2.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - torchinfo==1.8.0
    - torchio==0.19.1
    - torchmetrics==1.1.1
    - tqdm==4.62.3
    - typer==0.9.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - umap-learn==0.5.2
    - urllib3==1.26.16
    - wandb==0.12.11
    - werkzeug==2.3.7
    - wrapt==1.15.0
    - yarl==1.9.2
    - yaspin==2.5.0
    - zipp==3.16.2
